Check if git lfs is installed
r-three/git-theta pull request #145
Opened 2023-01-18 02:17 UTC by muqeeth

2023-01-18 03:01 UTC, blester125 requested changes
A few things to tweak.

Also please make sure to make new branches for new features and make sure they are branches from main (not your old branch). I'm seeing a lot of changes from the sparse update branching which makes it hard to tell which code is actually new.

2023-01-19 20:17 UTC, muqeeth commented on bin/git-theta
> +    if not git_utils.is_git_lfs_installed():
I did not actually run it here. I ran in ipython. I will change things now

2023-01-19 20:28 UTC, muqeeth commented
Looks if the git-lfs is not installed, we get the following for `results` object in `is_git_lfs_installed` function:

`CompletedProcess(args=['git', 'lfs', 'version'], returncode=1, stdout=b'', stderr=b"git: 'lfs' is not a git command. See 'git --help'.\n\nThe most similar command is\n\tlog\n")`

If the git-lfs is installed, we get:
`CompletedProcess(args=['git', 'lfs', 'version'], returncode=0, stdout=b'git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)\n', stderr=b'')`

2023-01-20 00:35 UTC, blester125 approved these changes

2023-01-20 06:18 UTC, merged